title: Serena's Site
author: Serena Huang
email: shuang3@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Hi! My name is Serena; this is my first time trying GitHub

# social links
instagram_username: serena.h678 # DO NOT include the @ character, or else the build will fail!
github_username:  serenah678 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-modernist
